version: '3.8'

services:
  # Base de datos
  db:
    image: mysql:8.0
    container_name: db_innovatech
    restart: always
    environment:
      MYSQL_DATABASE: db_sistema
      MYSQL_ROOT_PASSWORD: password_seguro
    ports:
      - "3306:3306"
    volumes:
      -db_data:/var/lib/mysql
    networks:
      - backend_net 
    
  # Microservicio de Despachos
  back-despachos:
    build: 
      context: "./proyecto semestral/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO"
      dockerfile: Dockerfile
    container_name: api_despachos
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_sistema
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password_seguro
    depends_on:
      - db
    networks:
      - backend_net

  # Microservicio de Ventas
  back-ventas:
    build: 
      context: "./proyecto semestral/back-Ventas_SpringBoot/Springboot-API-REST"
      dockerfile: Dockerfile
    container_name: api_ventas
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_sistema
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password_seguro
    depends_on:
      - db
    networks:
      - backend_net

  # Frontend (Acesso Público)
  frontend:
    build: 
      context: "./proyecto semestral/front-despacho"
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: unless-stopped
    ports:
      - "80:8080"
    networks:
      - backend_net

  # Redes y Volúmenes
networks:
  backend_net:
    driver: bridge

volumes:
  db_data: